// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6N3OuHbJ2vgI04rhabwher6VDtI8rgXk',
    appId: '1:1239596953:web:0eb64a6c6925728d065d08',
    messagingSenderId: '1239596953',
    projectId: 'registerpage-bf252',
    authDomain: 'registerpage-bf252.firebaseapp.com',
    storageBucket: 'registerpage-bf252.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVmbvlkmDNdMBTHw3lQkzDW2KpMci-0TM',
    appId: '1:1239596953:android:11451ed07d433818065d08',
    messagingSenderId: '1239596953',
    projectId: 'registerpage-bf252',
    storageBucket: 'registerpage-bf252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQjH9a6VNTWB1LY8Vd7nYp1mFN6inNOA',
    appId: '1:1239596953:ios:8f1afac0c6d392ab065d08',
    messagingSenderId: '1239596953',
    projectId: 'registerpage-bf252',
    storageBucket: 'registerpage-bf252.firebasestorage.app',
    iosBundleId: 'com.example.registerPageFirebase',
  );

}