// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDodtK2dHQtrRY4x_oSJ-Jvuvs15GgHoq4',
    appId: '1:323505439868:web:8be5dcf05d4382bb6675f9',
    messagingSenderId: '323505439868',
    projectId: 'notisflutter',
    authDomain: 'notisflutter.firebaseapp.com',
    storageBucket: 'notisflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe4_2v_QiY8QCzbRk_IDAiyONwyE6iaXQ',
    appId: '1:323505439868:android:870b1245c9c19cc66675f9',
    messagingSenderId: '323505439868',
    projectId: 'notisflutter',
    storageBucket: 'notisflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATW6ZKQULHO9BJ2e5Bcrvy6cPEm4JGTeM',
    appId: '1:323505439868:ios:1eb038f69d541c1d6675f9',
    messagingSenderId: '323505439868',
    projectId: 'notisflutter',
    storageBucket: 'notisflutter.firebasestorage.app',
    iosBundleId: 'com.example.actividadNotificaciones',
  );
}
